### ISSUE TITLE
Run test suite on a windows runner as well to catch platform-specific regressions

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#1034]
GH actions supports executing stuff on windows runners, so this should be quite simple to set up.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#overview-of-github-hosted-runners

**Comment by qTipTip** [comment]
For this we need to find a way of installing the `GDAL` binaries for the windows runner. Not quire sure how to do this yet.

**Comment by qTipTip** [comment]
It seems like one can optionally install the package `pyogrio` which comes with pre-installed binaries of GDAL for windows. I just need to figure out how to make sure `pyogrio` is installed __before__ the `geopandas` (and `fiona`) is installed.

**Comment by haakonvt** [comment]
Solved by @doctrino in #1213
