### ISSUE TITLE
Flaky test: `TestAssetPosterWorker.test.run`

### ISSUE THREAD

**Issue by haakonvt** [cognitedata/cognite-sdk-python#1112]
**Describe the bug**
In our build workflow, the test `TestAssetPosterWorker.test.run` may randomly fail (probably due to the magic and unpredictable world of threads...)

**Expected behavior**
Not be flaky.

**Screenshots**
<img width="989" alt="Screenshot 2023-01-11 at 15 17 46" src="https://user-images.githubusercontent.com/8521241/211831083-255877af-aaa9-4e64-aa35-d8b4f6cb5841.png">

**Comment by haakonvt** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/8521241/213824798-d0ea501e-1b2b-4d9e-a272-56a320e50c16.png">

**Comment by erlendvollset** [comment]
Closing this as we think we've addressed the issue. Please reopen if the issue persists.
