### ISSUE TITLE
Bug in the not-documentation of TimeSeries `isStep` parameter

### ISSUE THREAD

**Issue by evancharlton** [cognitedata/cognite-sdk-python#124]
The parameter is documented as `isStep`, but it's actually `is_step`. Since [the DTO](https://doc.cognitedata.com/0.5/#schemaposttimeseriesv2dto) is documented as `isStep`, I don't know what the right solution is.

But I do know it's [not a bug](https://cognitedata.slack.com/archives/C85QG3UBU/p1539089928000100?thread_ts=1539089156.000100&cid=C85QG3UBU) in the documentation!

**Comment by erlendcognite** [comment]
Fixed in #126
