### ISSUE TITLE
Support Python 11 for Cognite Functions

### ISSUE THREAD

**Issue by vancromy** [cognitedata/cognite-sdk-python#1302]
Cognite Functions does not yet support Python 3.11 as per the docs:
https://github.com/cognitedata/cognite-sdk-python/blob/a6c0a3a462fdeb82c904d4e6babbb161916d0abc/cognite/client/_api/functions.py#L124C1-L124C281

Python 3.11 is in bugfix status with 3.11.0 final released back in October 2022. We are already past bugfix cycle 4 (i.e. 3.11.4) ref: https://peps.python.org/pep-0664/

Python 3.11 boasts a significant speed increase which would be nice to make use of in deployed functions.

**Comment by qTipTip** [comment]
Hello! 👋 

We are utilising a few different backends for Cognite Functions depending on the cloud provider in question. I see that Azure Functions fairly recently has added support for Python 3.11, so I'll add this to our backlog. 😃
