### ISSUE TITLE
Threed endpoint doesn't support datasets for model creation

### ISSUE THREAD

**Issue by pavelzubarev** [cognitedata/cognite-sdk-python#1433]
**Is your feature request related to a problem? Please describe.**
```python    
  def create(self, name: str | Sequence[str]) -> ThreeDModel | ThreeDModelList:
        """`Create new 3d models. <https://developer.cognite.com/api#tag/3D-Models/operation/create3DModels>`_
```
API description allows to specify dataset.

**Describe the solution you'd like**
It would be nice to support dataset_id on the moment of 3d model creation

**Comment by haakonvt** [comment]
@pavelzubarev supported now (+metadata) in `6.34.1` 😄 . Closing.
