### ISSUE TITLE
Use expires_in to decide if a token should be refreshed

### ISSUE THREAD

**Issue by muradsater** [cognitedata/cognite-sdk-python#1602]
**System information (please complete the following information):**
 - SDK Version: 7.15

**Describe the bug**
When using client credentials the auth token is refreshed every 5 minutes, the expires_in property from the token-request is not used. The SDK reads a property named expires_at, but it's not a part of the RFC and not something AUTH0 and Entra return.

(most likely the case for user based flows as well)

**Expected behavior**
Refresh token only in_leeway_seconds before it is expiring.

**Screenshots**
Sample from an extractor, where the token has a lifetime of 24 hours.
<img width="1078" alt="image" src="https://github.com/cognitedata/cognite-sdk-python/assets/51971968/1302e441-6484-4e69-a015-d08e453dce6b">

**Comment by haakonvt** [comment]
Closing as the SDK now uses `expires_in` as of `7.26.2`
