### ISSUE TITLE
Type checker cannot infer types when accessing by index in `WriteableCogniteResourceList`

### ISSUE THREAD

**Issue by bastbu** [cognitedata/cognite-sdk-python#1648]
**System information (please complete the following information):**
 - OS: WSL2
 - Python Version: `Python 3.9.18`
 - SDK Version: `cognite-sdk==7.24.0`

**Describe the bug**

When using Pyright (with strict mode enabled), the following code generates an error (`error: Type of "d" is unknown (reportUnknownVariableType)`):

```py
from cognite.client import CogniteClient

client = CogniteClient()
data_sets_list = client.data_sets.list(limit=-1)
d = data_sets_list[0]
```

I think that the underlying issue is that the implementation for `WriteableCogniteResourceList` does not specify the generic type argument for its base class, e.g.

```py
class WriteableCogniteResourceList(CogniteResourceList, Generic[T_WriteClass, T_WritableCogniteResource]):
    @abstractmethod
    def as_write(self) -> CogniteResourceList[T_WriteClass]:
        raise NotImplementedError()
```

should be

```py
class WriteableCogniteResourceList(CogniteResourceList[T_WritableCogniteResource], Generic[T_WriteClass, T_WritableCogniteResource]):
    @abstractmethod
    def as_write(self) -> CogniteResourceList[T_WriteClass]:
        raise NotImplementedError()
```

and then the type of `d` is known.

**To Reproduce**

Enable Pyright strict mode and lint the following piece of code:

```
from cognite.client import CogniteClient

client = CogniteClient()
data_sets_list = client.data_sets.list(limit=-1)
d = data_sets_list[0]
```

**Expected behavior**

No linting errors should be emitted

**Comment by haakonvt** [comment]
@bastbu thanks for raising this issue! Seems to me that your suggested fix works as expected. Let me know if you want to be the one providing the fix/PR 😄

**Comment by bastbu** [comment]
Thanks for creating the PR! I'm fine with not supplying the fix for this 😄

**Comment by haakonvt** [comment]
@bastbu would you mind checking if `>=7.25.0` addresses the issue?

**Comment by bastbu** [comment]
Can confirm, this addresses the issue. Thanks for the fix!
