### ISSUE TITLE
 Invalid escape sequence '\_' in */client/data_classes/data_modeling/query.py (line 78) causes raising SyntaxError while running tests

### ISSUE THREAD

**Issue by andrii-sventukh-MDTU-VOL** [cognitedata/cognite-sdk-python#1650]
**System information (please complete the following information):**
 - OS: [Debian]
 - Python Version: [3.11]
 - SDK Version: [7.24.0]

**Describe the bug**
While running pytest for code using cognite-sdk error SyntaxError: invalid escape sequence '\_' arises  due to probably typo in /client/data_classes/data_modeling/query.py", line 78
![error](https://github.com/cognitedata/cognite-sdk-python/assets/122725949/b82b826b-6a27-44ca-8fb0-03ffcbee42e7)

**To Reproduce**
run
```
poetry run pytest
```
for code containing import "from cognite.client._cognite_client import CogniteClient"

**Expected behavior**
no errors, as just cognite-sdk version has been changed from 6.* to 7.*

**Screenshots**
![docstring in version 6](https://github.com/cognitedata/cognite-sdk-python/assets/122725949/ff6ed8a2-a4dd-4bb5-b8be-6940bf52c36e)
![docstring in version 7](https://github.com/cognitedata/cognite-sdk-python/assets/122725949/d6b1d2f8-fd38-4395-aa01-a8d4128f3251)

Just adding "r" before """docstring""" or removing "\" from the one in /client/data_classes/data_modeling/query.py", line 78 solves the issue

**Comment by haakonvt** [comment]
Hi @andrii-sventukh-MDTU-VOL and thanks for raising the issue! This is an oversight, thanks! I've made a fix here: https://github.com/cognitedata/cognite-sdk-python/pull/1651

**Comment by andrii-sventukh-MDTU-VOL** [comment]
Thanks a lot! Will the fixed version be available on PyPI soon?
