### ISSUE TITLE
Pyright reports error related to type `SequenceNotStr`

### ISSUE THREAD

**Issue by bastbu** [cognitedata/cognite-sdk-python#1720]
**System information (please complete the following information):**
 - OS: WSL2
 - Python Version: 3.11.9
 - SDK Version: 7.32.2

**Describe the bug**

When linting the following code with Pyright:

```python
from cognite.client import CogniteClient

client = CogniteClient()
client.raw.databases.delete(["db1", "db2"])
```

It reports the following error:

```
error: Argument of type "list[str]" cannot be assigned to parameter "name" of type "str | SequenceNotStr[str]" in function "delete"
    Type "list[str]" cannot be assigned to type "str | SequenceNotStr[str]"
      "list[str]" is incompatible with "str"
      "list[str]" is incompatible with protocol "SequenceNotStr[str]"
        "index" is an incompatible type
          Type "(value: str, start: SupportsIndex = 0, stop: SupportsIndex = sys.maxsize, /) -> int" cannot be assigned to type "(value: Any, /, start: int = 0, stop: int = ...) -> int"
            Position-only parameter mismatch; parameter "start" is not position-only
            Position-only parameter mismatch; parameter "stop" is not position-only (reportArgumentType)
```

There seem to be issues with the `SequenceNotStr` protocol defined, as changing

```
def index(self, value: Any, /, start: int = 0, stop: int = ...) -> int: ...
```

to

```
def index(self, value: Any, start: int = 0, stop: int = ..., /) -> int: ...
```

addresses the linting errror. I am not claiming that this is the correct fix (I haven't dug deeper around the intentions of `SequenceNotStr`), just sketching out what solves the issue for me.

**To Reproduce**

Install Pyright, and enable the errors on the `reportArgumentType` diagnostic.

```python
from cognite.client import CogniteClient

client = CogniteClient()
client.raw.databases.delete(["db1", "db2"])
```

**Expected behavior**

No linting errors should be generated.

**Comment by haakonvt** [comment]
`class list` in typeshed is defined like your fix: https://github.com/python/typeshed/blob/7c8e82fe483a40ec4cb0a2505cfdb0f3e7cc81d9/stdlib/builtins.pyi#L984

**Comment by haakonvt** [comment]
@bastbu please update to the latest release and reopen if the issue still persists! 😄
