### ISSUE TITLE
CogniteClient.get throws exception

### ISSUE THREAD

**Issue by matiashf-cognite** [cognitedata/cognite-sdk-python#184]
When I run
```python
from cognite import CogniteClient
CogniteClient().get('/login')
```

I get the following error:
> ...
> File ".../cognite/client/cognite_client.py", line 164, in get
>     return self._api_client._get(url, params, headers)
> File ".../cognite/client/_api_client.py", line 61, in wrapper
>     res = method(client_instance, full_url, *args, **kwargs)
> TypeError: _get() got multiple values for argument 'headers'

The error is caused by the default `params` and `header` arguments (with the value of `None`) being passed as positional arguments to `wrapper`, which then adds keyword arguments before calling the wrapped `_get` method.

This problem probably applies to other functions wrapped by `request_method`, like `post` and `delete`.

I worked around the bug by bypassing the wrapper with `CogniteClient()._api_client._get('/login')`.

**Comment by erlendcognite** [comment]
Addressed in #185
