### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by Hidjikimi** [cognitedata/cognite-sdk-python#187]
In Cognite SDK documentation in section Datapoints -> post_datapoints this Python code generate an error:

from cognite.client.stable.datapoints import Datapoint
client = CogniteClient()
start = 1514761200000
my_dummy_data = [Datapoint(timestamp=ms, value=i) for i, ms in range(start, start+100)]
client.datapoints.post_datapoints(my_dummy_data)

TypeError: cannot unpack non-iterable int object

Also post_datapoints should get two parameters instead of one in example.

**Comment by hermord** [comment]
#189 fixes this.
