### ISSUE TITLE
DataTransferService creates new client by default

### ISSUE THREAD

**Issue by matiashf-cognite** [cognitedata/cognite-sdk-python#194]
The DataTransferService creates its own client, and users are easily confused into connecting to two different projects simultaneously.

Suppose I have the following variables set:
```sh
export COGNITE_API_KEY=xyz789 # for default_project
export MY_PROJECT_API_KEY=abc123 # For my_project
```

Then I naively read the documentation and do this:
```python
from cognite import CogniteClient
from cognite.data_transfer_service import DataTransferService

client = CogniteClient(api_key=os.environ.get('MY_PROJECT_API_KEY'), project='my_project')
dts = DataTransferService()  # Will actually access 'default_project' with COGNITE_API_KEY!
```

I'm actually accessing two different projects with two different api keys, though this is not immediately apparent. To work around this, I have to *always* remember to explicitly pass `api_key` when creating a `DataTransferService` instance. That's a burden we should not put on our users.

Suggested fixes:
1. If using `COGNITE_API_KEY`, issue a warning like `Warning: Using the COGNITE_API_KEY environment variable to connect to the CDP project 'default_project'`
2. Change that signature of `DataTransferService` to take `client` as an optional parameter, and not `api_key`, `cookies` or `num_of_workers`. If no client is given, a new one is created.
3. Implement a getter `client.data_transfer_service` that returns `DataTransferService(client=self)`.
4. Extend the documentation for DataTransferService to explicitly mention that a new client is created if none is given, and suggest to use `cognite.data_transfer_service` instead.

**Comment by erlendvollset** [comment]
We are removing data transfer service in the new SDK version. To be replaced with separate package. So closing this.
