### ISSUE TITLE
Add flag to include/exclude time series metadata in TimeSeriesResponse.to_pandas()

### ISSUE THREAD

**Issue by patrickrobertson** [cognitedata/cognite-sdk-python#196]
When getting multiple time series by ID, and they have very different metadata, it would be nice to choose whether or not all metadata fields should be separate columns in the resulting dataframe (when calling to_pandas()). I.e. something like to_pandas(show_metadata=False), which would result in a Pandas dataframe with a single column containing the metadata as dict.

**Comment by erlendcognite** [comment]
#197
