### ISSUE TITLE
LatestDatapointResponse.to_json() throws IndexError for time series without data points

### ISSUE THREAD

**Issue by matiashf-cognite** [cognitedata/cognite-sdk-python#201]
When I run

```python
client.datapoints.get_latest('ts_without_datapoints').to_json()
```

I get the exception
```
.../cognite/client/stable/datapoints.py in to_json(self)
    114     def to_json(self):
    115         """Returns data as a json object"""
--> 116         return self.internal_representation["data"]["items"][0]
    117 
    118     def to_pandas(self):

IndexError: list index out of range
```

Where
```python
self.internal_representation = {'data': {'items': []}}
```

This is confusing, and at first glance seemed like a bug in the SDK. A more user friendly approach would be to either:
* throw a custom exception e.g. `NoDatapointsException` when calling `get_latest`
* return None from `to_json()`

I would prefer the former, or optionally have a flag to control the behavior.

**Comment by erlendcognite** [comment]
Agreed. Should raise a custom exception in this case.

**Comment by erlendvollset** [comment]
This has been fixed in #307, and will be released in version 1.0.0

**Comment by haakonvt** [comment]
Was broken again after #633 (still is)

**Comment by haakonvt** [comment]
Wrong issue 🤦
