### ISSUE TITLE
Timeseries documentation typo, get_time_series()

### ISSUE THREAD

**Issue by datakristy** [cognitedata/cognite-sdk-python#226]
![image](https://user-images.githubusercontent.com/46494163/52201416-a072ca80-286b-11e9-8564-bc4f51dbf32c.png)
This example in the newest docs show the function `get_timeseries`, but this function doesn't exist anymore! `get_time_series` is the new function.

The screenshot is the first code example in https://cognite-sdk-python.readthedocs-hosted.com/en/latest/cognite.html

**Comment by erlendcognite** [comment]
Addressed in #227
