### ISSUE TITLE
numpy.int64 not accepted by sdk

### ISSUE THREAD

**Issue by gzarruk** [cognitedata/cognite-sdk-python#242]
Seems like CDP doesn't know how to handle int64. When pushing data that is type numpy.int64 I get an error. Changing it to float or to int fixes the issue. Several others have encountered the same issue since  numpy.int64 is a very common type used. It would be good to have this type supported by the python-sdk.

![image 1](https://user-images.githubusercontent.com/24595022/52932588-8992a480-3350-11e9-9ae5-1d45a27ded5d.png)

**Comment by erlendvollset** [comment]
Could you provide some code to reproduce, @gzarruk?

**Comment by gzarruk** [comment]
Here is the code and a csv file to reproduce the error. 
At the end of the notebook, just remove the "astype(float)" at the end of penultimate line.
[Archive.zip](https://github.com/cognitedata/cognite-sdk-python/files/2897844/Archive.zip)

**Comment by erlendvollset** [comment]
Handled in #250
