### ISSUE TITLE
Support for update asset

### ISSUE THREAD

**Issue by maciejmrowiec** [cognitedata/cognite-sdk-python#259]
**Describe the solution you'd like**
Support for updating selected asset through SDK (stable)

Currently using SDK need to recreate the asset or use API directly outside SDK.

**Additional context**
0.5 API supports this operation though: https://doc.cognitedata.com/api/0.5/#operation/alterAssets

**Comment by erlendvollset** [comment]
I'll get this done before the weekend. In the meantime you can use CogniteClient().post("/api/0.5/projects/<your-project>/assets/update", body={...}) instead.

**Comment by maciejmrowiec** [comment]
@klunacognite

**Comment by erlendvollset** [comment]
Addet update_asset() and update_assets() in 0.13.0a8
