### ISSUE TITLE
Use Retry-After header after 429/503

### ISSUE THREAD

**Issue by f1cognite** [cognitedata/cognite-sdk-python#268]
**Is your feature request related to a problem? Please describe.**
We can some `429` issues from backend, and we should use their suggested delay before next request.

**Describe the solution you'd like**
Use this header value as a parameter to the retry-function.

**Comment by erlendvollset** [comment]
As far as I have understood, none of our services will return this header @f1cognite. Can I close this Issue?

**Comment by f1cognite** [comment]
Yes
