### ISSUE TITLE
Get a specific time series using name or id

### ISSUE THREAD

**Issue by jaketbouma** [cognitedata/cognite-sdk-python#272]
**Is your feature request related to a problem? Please describe.**
I often have a time series id or name and would like to look up the metadata of the time series.
I'd like to be able to get a timeseries by id and by name.

**Describe the solution you'd like**
Two additional access patterns:
- `time_series.get_time_series(name='TIMESERIESNAME')`
- `time_series.get_time_series(id=1234567890123)`

Which return an error if the time series is found.

**Describe alternatives you've considered**
The `prefix` parameter of `time_series.get_time_series` works, but this is a search, that will return multiple results. Taking the first result in the response will lead to logical errors if done without additional checks.

**Additional context**
Open quesion: are time series names unique in CDP, or is it just the id?

**Comment by dshynkev** [comment]
It is possible to use `client.experimental.time_series.get_time_series_by_id`, which does return a unique result.

**Comment by erlendvollset** [comment]
@jaketbouma names are unique in 0.5, but not from 0.6 and onwards. So the solution proposed by @dshynkev here should be sufficient. Closing this issue, but feel free to reopen if this does not solve your problem.
