### ISSUE TITLE
Dead link in examples

### ISSUE THREAD

**Issue by johhat** [cognitedata/cognite-sdk-python#274]
**Describe the bug**
Dead link to pattern search in
https://github.com/cognitedata/cognite-sdk-python/tree/master/examples

**To Reproduce**
Check the link https://github.com/cognitedata/cognite-sdk-python/tree/master/examples

**Expected behavior**
No link. API deprecated.

**Comment by erlendvollset** [comment]
Pattern search has been deprecated, a PR for removing it from the README is in the making.
