### ISSUE TITLE
`type` argument doesn't work for `events.get_events` method

### ISSUE THREAD

**Issue by romanmotsar** [cognitedata/cognite-sdk-python#292]
**Describe the bug**
When you are trying to get events with specified `type` argument, it returns not only events with specified type

**To Reproduce**
```
from cognite.client import CogniteClient

cognite_client = CogniteClient()
asset_id = 8040340116462668

cursor_id = None
all_events = list()
while True:
  events_response = cognite_client.events.get_events(type="Workorder", asset_id=asset_id, autopaging=True)
  events = events_response.to_json()
  cursor_id = events_response.next_cursor()
  
  all_events.extend(events)
  
  if cursor_id is None:
    break


assert all([event['type'] == "Workorder" for event in all_events]), "Events contains not only `Workorders` events"
```
**Expected behavior**
All events should have `type='Workorder'`

**Screenshots**
In context of previous code snippet
![image](https://user-images.githubusercontent.com/47787026/54271882-b4a09a80-4582-11e9-8b73-5c38664df2f1.png)

**Additional context**
Also, I have the same process with `type='Isolation_Certificate` and it's not working

**Comment by romanmotsar** [comment]
cognite==0.12.15

**Comment by erlendvollset** [comment]
Parameters 'type', 'subtype', 'hasDescription', 'minStartTime', 'maxStartTime' and 'source' are disabled when assetId is used. This user error is being hidden by the SDK. I have added #306 to address this issue.

**Comment by erlendvollset** [comment]
As a workaround, I suggest filtering only on `type` or `asset_id` in the request, and then filtering on the other locally.

**Comment by romanmotsar** [comment]
@erlendvollset 
Why we can't apply two filters at the same time? Maybe some objectives on it?
It seems non-efficient way to fetch a "big" amount of data and then filter it again

E.g. when we need isolation_certificates for specific asset_id we need to make GET request (or maybe multiple if we have more than 10K events), transfer this data through internet, keep in memory and filter to get only few records

**Comment by erlendvollset** [comment]
This is is not a limitation in the SDK, but in the API. This behaviour will improve in v1 though, where arbitrary combinations of filters can be applied.
