### ISSUE TITLE
Handle decimals when serializing to json

### ISSUE THREAD

**Issue by s38feng** [cognitedata/cognite-sdk-python#311]
**Describe the bug**
The Cognite SDK (Python) is unable to handle decimal values. Specifically, we ran into this issue when we were attempting to run the db-extractor, which uses the `cognite.client.stable.raw.RawRow` class.

**To Reproduce**
Runnable code reproducing the error.
```
import decimal

from cognite.client import CogniteClient
from cognite.client.stable.raw import RawRow

client = CogniteClient()

RawRow("test_key", {"test_column": decimal.Decimal(2)})
```
**Expected behavior**
Up for debate about how crucial this is, as we can theoretically handle this on our end, but it is proposed that Cognite SDK should convert/handle values of decimal data type. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46494379/55000441-ca767c80-4fd2-11e9-8f9d-b36ed01c9bdf.png)
Error that we got when running the db-extractor

**System information (please complete the following information):**
 - OS: MacOS & Linux
 - Python Version: Python 3.7.2
 - SDK Version: 0.12.12

**Comment by jesuejunior** [comment]
Hello,

I see two ways to solve it.

1. Use simplejson library

<img width="258" alt="Screen Shot 2019-04-02 at 22 24 35" src="https://user-images.githubusercontent.com/813235/55446477-338f5e80-5596-11e9-905d-a6cb6e08b000.png">

* I have had tested locally and it worked well
<img width="526" alt="Screen Shot 2019-04-02 at 22 20 44" src="https://user-images.githubusercontent.com/813235/55446495-45710180-5596-11e9-862d-1aad2c3ebafc.png">

And I just needed to do this and everything worked as known.

<img width="503" alt="Screen Shot 2019-04-02 at 22 24 03" src="https://user-images.githubusercontent.com/813235/55446520-5f124900-5596-11e9-8c4f-f9ec3b7d6a23.png">

2. Write the own decoder like this one and It will demand much more changes in the code appying cls in ao `json.dumps`

<img width="494" alt="Screen Shot 2019-04-02 at 22 28 41" src="https://user-images.githubusercontent.com/813235/55446602-b4e6f100-5596-11e9-9f0a-6cdac18345f9.png">

Of course I did some tests to cover this point.

If the @erlendvollset  allow me I can open the PR quickly as possible and changing all import points as well.

Make sense?

**Comment by erlendvollset** [comment]
Handled in #307. Will be released in 1.0.0.

**Comment by andersholtecognite** [comment]
We still have problems with Decimal datatype conversion to json in the latest SDK. 
Anything I have to do to enable it?

These are the versions I'm running with Pytjon 3.7:
  - cognite-sdk [required: Any, installed: 1.0.4]
  - cognite-uploader [required: Any, installed: 2.1.1]

**Comment by erlendvollset** [comment]
Could you please provide a code sample to reproduce?

**Comment by andersholtecognite** [comment]
Not give you a sample snippet... I'm using it through dbextractor and the dataset is a resultset from SQL Server. This is the full stacktrace:

  File "extract.py", line 6, in <module>
    main()
  File "C:\cognite\dbextractor\dbextractor\main.py", line 514, in main
    extractor.extract()
  File "C:\cognite\dbextractor\dbextractor\extractor.py", line 171, in extract
    Row(row_key, columns)
  File "C:\Users\Anders\.virtualenvs\dbextractor-FdoGtbds\lib\site-packages\cognite_uploader\cognite_uploader.py", line 135, in add_to_upload_queue
    self._inner_add_to_queue(database, table, raw_row)
  File "C:\Users\Anders\.virtualenvs\dbextractor-FdoGtbds\lib\site-packages\cognite_uploader\cognite_uploader.py", line 64, in _inner_add_to_queue
    self.upload_queue_byte_size += len(repr(obj))
  File "C:\Users\Anders\.virtualenvs\dbextractor-FdoGtbds\lib\site-packages\cognite\client\data_classes\_base.py", line 70, in __repr__
    return self.__str__()
  File "C:\Users\Anders\.virtualenvs\dbextractor-FdoGtbds\lib\site-packages\cognite\client\data_classes\_base.py", line 67, in __str__
    return json.dumps(item, default=lambda x: x.__dict__, indent=4)
  File "C:\Python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\Lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\Python37\Lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Python37\Lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Python37\Lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Python37\Lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Anders\.virtualenvs\dbextractor-FdoGtbds\lib\site-packages\cognite\client\data_classes\_base.py", line 67, in <lambda>
    return json.dumps(item, default=lambda x: x.__dict__, indent=4)
AttributeError: 'decimal.Decimal' object has no attribute '__dict__'

**Comment by erlendvollset** [comment]
I have created a PR to fix this. 

But looking at the traceback you have provided I would not recommend relying on len(repr(obj)) to determine the number of bytes an object consists of. I would use sys.getsizeof(obj) or sys.getsizeof(obj.dump()), depending on what you are looking for the size of. Not only is it incorrect to use that number, but `__repr__` also returns a string which may change at the developers discretion, there are no guarantees on backwards compatibility on the return value of that method.
