### ISSUE TITLE
cognite package is missing __version__ tag

### ISSUE THREAD

**Issue by MattBreelandCognite** [cognitedata/cognite-sdk-python#319]
**Describe the bug**
The cognite package is missing a __version__ tag.

**To Reproduce**
Runnable code reproducing the error.
```
import cognite
print(cognite.__version__)
```
**Expected behavior**
The version should be printed. Something like "0.13.2"

**System information (please complete the following information):**
 - OS: x86_64-64bit
 - Python Version: CPython/3.7.2
 - SDK Version: lolz 0.13.2

**Comment by erlendvollset** [comment]
We have several packages under the cognite namespace like `cognite.logger`, `cognite.model_hosting`, and `cognite.client`, so it wouldn't make sense (and is not feasible) to have a version in the top-level. 

You can find the `__version__` attribute under those namespaces. e.g. 
```
import cognite.client
print(cognite.client.__version__)
```
