### ISSUE TITLE
Visualize hierarchy of assets 

### ISSUE THREAD

**Issue by lynochka** [cognitedata/cognite-sdk-python#325]
I believe there is no way to visualize the hierarchy of a small asset subset (few top-layer assets for the entire data or in a subtree. SImilar to 
```
Node('/Mary')
├── Node('/Mary/Urs')
│      name: Urs Ivanova
│      created: 1989/08/24
│      possible meta data: likes to run
├── Node('/Mary/Chris')
├── Node('/Mary/Marta')
└── Node('/Mary/Udo')
    ├── Node('/Mary/Udo/Marc')
    │   └── Node('/Mary/Udo/Marc/Lian')
    └── Node('/Mary/Udo/Dan')
        ├── Node('/Mary/Udo/Dan/Jet')
        ├── Node('/Mary/Udo/Dan/Jan')
        └── Node('/Mary/Udo/Dan/Joe')
```
(Inspired by a https://anytree.readthedocs.io)

This is the output. The method could be provided an argument to include asset metadata (such as name, or other keys of the asset dictionary if they exist).

The call can be based on a list of assets (given by asset IDs). Or pure explore call starting with an asset ID and going deep this many layers.

This is also a great way to show that multiple disconnected trees exist in the hierarchy if the method allows calls without a root node (dummy root node).

**Additional context**
We need to see how much exploration is done in the SDK and where SDK is ahead of API (exploration through visualization might be one such case).

**Comment by erlendvollset** [comment]
I've implemented this in #320 so it will be released for v1.
