### ISSUE TITLE
Dataframe functionality in SDK - API v1 

### ISSUE THREAD

**Issue by maciejmrowiec** [cognitedata/cognite-sdk-python#350]
API v1 is removing dataframe endpoints for retrieving datapoints due to it's tight overlap with datapoint retrieval. Main difference was in how the output was formatted.

Introduce equivalent functionality purely on SDK side based on retrieve datapoints endpoint.

Targeted behaviour: https://doc.cognitedata.com/api/0.5/#operation/getDatapointsFrame
Underlying data source: https://doc.cognitedata.com/api/v1/#operation/getMultiTimeSeriesDatapoints

Intended for SDK 1.0

**Comment by maciejmrowiec** [comment]
equivalent for JS sdk (possible you'll need to sync on the details) https://github.com/cognitedata/cognitesdk-js/issues/82

**Comment by erlendvollset** [comment]
This has already been implemented.

**Comment by maciejmrowiec** [comment]
nice!
