### ISSUE TITLE
Add integration with Cognite's login flow to support non-api-key users

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#371]
@johannes-kk mentioned that some customers will require that we support an alternative to api-key authentication where users can login with their AD.

@f1cognite fyi

**Comment by f1cognite** [comment]
@erlendvollset How are you thinking to implement this?

**Comment by erlendvollset** [comment]
This guide made by @f1cognite documents how this should be implemented.
https://github.com/cognitedata/cognitesdk-js/blob/v1/guides/authentication.md
