### ISSUE TITLE
Don't merge multiple DatapointsQuery into one result

### ISSUE THREAD

**Issue by sanderland** [cognitedata/cognite-sdk-python#391]
**Describe the bug**
When using datapoints.query, queries with the same id are merged into one result. This is intuitive and possible unhelpful.

**Usecase**
Getting several stretches of datapoints with different start/end for the same id (for example, those with certain quality requirements, or where events did or didn't happen).

**Expected behaviour**
query() always returns a list of the same length as the queries parameter, with each result corresponding to queries in the same order.

NB: to_pandas() in DataPointsList will probably need some adapting as well, since I think it makes the same assumption of no duplicate ids.

**Comment by erlendvollset** [comment]
Decided to raise exception when attempting to retrieve multiple time series with same id in a single call. They way the DatapointsList object is constructed, it requires that they are unique. This issue can be solved in the client by doing several concurrent calls to .retrieve(). Multiple aggregates for the same ts in a single call is of course still supported.

If this is a very common use case, we can revisit and implement it in the SDK. Will close this issue for now. Feel free to reopen.
