### ISSUE TITLE
_check_client_has_newest_major_version should not cause a failure

### ISSUE THREAD

**Issue by sanderland** [cognitedata/cognite-sdk-python#416]
**Describe the bug**
On the an important customer's environment, pypi.python.org can not be reached, and they use their own artifactory. This causes an exception:
SSLError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/cognite-sdk/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**fix**
Print a warning instead of failing, or just ignore the failure, since its not critical.

**Comment by erlendvollset** [comment]
You can disable this check by setting this environment variable: `COGNITE_DISABLE_PYPI_VERSION_CHECK = "1"`

**Comment by sanderland** [comment]
I don't think so, not being able to connect to some version check the user never asked for and at worst gives a warning is not a reason to throw an exception.

**Comment by erlendvollset** [comment]
Agreed. We should catch this exception and ignore it.
