### ISSUE TITLE
AssetList.files() and AssetList.events() may yield duplicates

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#419]
Since files and events can point to multiple asset ids, duplicates may end up in the resulting resource lists returned from these methods. Duplicates should be filtered out from the returned resource lists.

**Comment by HMEiding** [comment]
Not able to reproduce this bug. After adding an event/file which points to two assets, calling AssetList.events() and AssetList.files() on an AssetList including the two assets only returns the event/file once. For example, the following code:

`from cognite.client import CogniteClient

c = CogniteClient()

asset_list = c.assets.list(limit=5)
id1 = asset_list[0].id
id2 = asset_list[1].id

print("id1: ", id1)
print("id2: ", id2)

events = asset_list.events()

print(events)`

returns:

`id1:  1107794733179
id2:  1137521939646
[
    {
        "start_time": "1970-01-01 00:00:00",
        "end_time": "1970-01-01 00:00:00",
        "asset_ids": [
            1107794733179,
            1137521939646
        ],
        "id": 5550017793452559,
        "last_updated_time": "2019-07-05 09:12:55",
        "created_time": "2019-07-05 09:12:55"
    }
]`

**Comment by erlendvollset** [comment]
It will only happen if there are more than 100 assets in the AssetList. Then the resources linked to those assets may be retrieved in different requests and the results concatenated client side.
