### ISSUE TITLE
Retrieving datapoints will fail if aggregation jobs are queued up.

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#421]
The current method for retrieving datapoints uses count aggregates to get the distribution of the data. If aggregates have not been created for some newly posted datapoints yet, the current implementation of the DatapointsFetcher will fail.

**Comment by sanderland** [comment]
only of 10k datapoints are retrieved and no aggregates at all exists for the same time period, which should be super rare. anyway, I think this fixes it:

if not res:
  return [_DPWindow(start, end)]
