### ISSUE TITLE
parent_external_id should not be validated by sdk

### ISSUE THREAD

**Issue by nodegard** [cognitedata/cognite-sdk-python#425]
**Describe the bug**
Cannot create asset hierarchy using parent_external_id when more than 1000 are posted, when the parent asset is not part of the request.

**To Reproduce**
Runnable code reproducing the error.
```
from cognite.client import CogniteClient
from cognite.client.data_classes.assets import Asset

client = CogniteClient()

# Make root
asset = Asset(external_id="root",
               name="name",
               description="description",
               metadata=None,
               source=None)

created = client.assets.create(asset)

# Make lots of children
assets = []
for i in range(1,1005):
  assets.append(Asset(external_id="child_{0}".format(i),
               name="name",
               description="description",
               metadata=None,
               source=None,
               parent_external_id="root"))
try:
  created = client.assets.create(assets)
except Exception as e:
  print(e)
```

**Expected behavior**
Request using parent external id should be allowed even when parent is not a part of the request.

**System information (please complete the following information):**
 - Python Version: CPython/3.5.2
 - SDK Version: 1.0.0a33

**Additional context**
Copying asset hierarchy from one tenant to another.

**Comment by eventh** [comment]
The current validating logic is flawed, it requires that the batch of nodes you are posting includes a root node. It is not possible to create more than 1000 assets in a hierarchy attached to an existing asset, when the relationship is defined by parent_external_id.

The only possible workaround is not using parent_external_id.
It would be better to remove this faulty validation as it doesn't provide any value except limit use cases that should be possible.

**Comment by erlendvollset** [comment]
If the parent_external_id set on an asset is not part of the batch of nodes you are posting, it should be treated as a "root" node on the client side, meaning that it should be subject to the same sorting of its descendants (in the same batch), and posted in that order. @HMEiding will address this issue and the other related to #469 in this sprint.
