### ISSUE TITLE
Python SDK 0.13 Bug on post_data_to_sequence()

### ISSUE THREAD

**Issue by youwucognite** [cognitedata/cognite-sdk-python#430]
**Describe the bug**
Under Sequences, the required parameters for post_data_to_sequence() do not correspond with api. When ingesting rows into sequence using post_data_to_sequence(), it requires to specify the column_id for each RowValue, but it is not required by api.

**To Reproduce**
```
from cognite.client import CogniteClient

client = CogniteClient()

client.experimental.sequences.post_data_to_sequence(id = , rows = [Row(row_number = 0, values = [RowValue(column_id = , value = "one row" )])])
```
**Expected behavior**
Expect a row under one column be ingested into a test tenant. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51821197/60654358-26f7fc00-9e4c-11e9-9bc9-119a6bf3f3a5.png)
![image](https://user-images.githubusercontent.com/51821197/60654394-3a0acc00-9e4c-11e9-88d1-2276dc01693c.png)
![image](https://user-images.githubusercontent.com/51821197/60654444-50b12300-9e4c-11e9-82a0-1680333fa8cd.png)
![image](https://user-images.githubusercontent.com/51821197/60654524-72120f00-9e4c-11e9-97b7-f23f249080e2.png)

**System information (please complete the following information):**
 - OS: [macOS Mojave Version 0.14.5 (18F203)]
 - Python Version: [Python 3.7.3]
 - SDK Version: [0.13_a]

**Additional context**

**Comment by erlendvollset** [comment]
We will not be doing bugfixes for experimental features marked as deprecated. You should use the new Sequences client in the 1.0 SDK.
