### ISSUE TITLE
Include time zone in time series

### ISSUE THREAD

**Issue by thibault-2s** [cognitedata/cognite-sdk-python#441]
Retrieving time series via TimeSeriesAPI.retrieve, the data received contains a time index without time zone. When visualizing the same data in OpInt, timestamps are not aligned. 

It would be really helpful to have the time zone as part of the time stamp.

An alternative is to have the time zone set similarly in the data source, OpInt and other services developed and communicated.

**Comment by erlendvollset** [comment]
All timestamps are UTC. IMO it should be the same in the applications.

**Comment by thibault-2s** [comment]
Thanks, fully agree. I will report that on the OpInt bug tracker then, if there is any.

**Comment by erlendvollset** [comment]
Will close this issue then. Feel free to reopen if the discussion should suggest that we need to change the behaviour in the SDK.
