### ISSUE TITLE
Implement client for sequences API

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#447]
Once sequences is ready for v1, it should have a client implemented in the SDK.

Link to the openapi spec for service (WIP):
https://github.com/cognitedata/service-contracts/pull/133

**Comment by erlendvollset** [comment]
@runevalle-cognite fyi

**Comment by runevalle-cognite** [comment]
@maciejmrowiec  you might want to track this as well.
