### ISSUE TITLE
Populate sequences data using test-data-populator

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#459]
Currently the data used for the sequences integration tests is populated manually. This should script should be rewritten into the test-data-populator so we ensure that the data is always there.

https://github.com/cognitedata/test-data-populator

**Comment by sanderland** [comment]
Are populators based on the old api/sdk only?

**Comment by erlendvollset** [comment]
Populators are based only on old SDK. This issue can wait until we have moved the populator to  v1.

**Comment by erlendvollset** [comment]
We actually want to get away from using the test-data-populator as much as we can, so closing this.
