### ISSUE TITLE
Implement .create() method on files API to allow creating file(s) without uploading

### ISSUE THREAD

**Issue by eventh** [cognitedata/cognite-sdk-python#460]
**Describe the solution you'd like**
The CDF API allows you to create a file with metadata, and not upload anything. The SDK should enable the same work flow, by making the path argument optional.

**Additional context**
The use case for this feature is that it enables us to create files with metadata, and later upload the content, so we can separate these two steps.

**Comment by greenbech** [comment]
This is sort of blocking me, so I can try to come up with a PR for this

**Comment by erlendvollset** [comment]
@HMEiding We have this on our backlog for the upcoming sprimt, @HMEiding will submit a PR.

**Comment by eventh** [comment]
Great, I'm on vacation so didn't have time to fix it myself :)

**Comment by eventh** [comment]
@erlendvollset @HMEiding did you guys create this?
