### ISSUE TITLE
Adapt to 0.5 endpoint changes

### ISSUE THREAD

**Issue by psalaberria002** [cognitedata/cognite-sdk-python#50]
# Breaking changes
## Storage/Files
- /storage (Cloud Storage) endpoints renamed to /files (Files)
- GET /api/0.5/projects/{project}/storage/{id}/info moved to /api/0.5/projects/{project}/files/{id} . Now returns a list with a single file.
- GET /api/0.5/projects/{project}/storage/{id} moved to /api/0.5/projects/{project}/files/{id}/downloadlink

## Assets
- GET /api/0.5/projects/{project}/assets/{id} moved to /api/0.5/projects/{project}/assets/{id}/subtree
- GET /api/0.5/projects/{project}/assets/{id} now returns a list with a single asset.

## Events
- GET /api/0.5/projects/{project}/events/{eventId} returns a list now with a single element

**Comment by erlendcognite** [comment]
Fixed in sdk v0.6.0
