### ISSUE TITLE
Set default value for limits on .search() methods.

### ISSUE THREAD

**Issue by tommyod** [cognitedata/cognite-sdk-python#518]
**Is your feature request related to a problem? Please describe.**

It would be better to use default arguments instead of `None` when there's an implicit default.
An example is:

https://github.com/cognitedata/cognite-sdk-python/blob/0436b46146dbd8ec2b8e660e215ac449efcdc205/cognite/client/_api/assets.py#L305

The default is set to `None`, but 100 results are returned. The docstring does not state that. The signature does not. In other words, there's an implicit default argument.

In the example below, the limit is written in the docstring, but not in the signature:
https://github.com/cognitedata/cognite-sdk-python/blob/e282939f88a1a851e1cfd28339943136e9dd83ae/cognite/client/_api/model_hosting/models.py#L65

In the example below, the limit is written in the docstring and in the signature:
https://github.com/cognitedata/cognite-sdk-python/blob/121db972432c32c0e34ddd03add5e221a1510292/cognite/client/_api/iam.py#L295

**Describe the solution you'd like**

I'd like default arguments not be "shadowed" by `None` in general.

```python
CONST = 100
    
    def f(x=CONST):
        pass

# help(f) gives "f(x=100)"
```

Ideally, limits and other integers would be in the signature (and not in the docstring) to avoid redundancy and having to remember to update two places if a change is made. 

**Describe alternatives you've considered**

Going through your source code to search to the limit. Binary search on the assets.

**Additional context**
Not relevant.

**Comment by erlendvollset** [comment]
Passing `None` will retrieve all results, since .search() will return a maximum of 1000 results, we do not set a client side limit. For the .list() methods we do pagination, so there we consistently set a reasonable default limit of 25, to reduce misuse of the underlying APIs.

We should set the same default limit for the .list() methods for model hosting, but we currently have a bug in the underlying API causing a 400 if we pass query parameters, so we do not set a default limit client side there, but rather communicate the default limit set by the API through the docstring. It will be fixed once we move it out of experimental.

**Comment by tommyod** [comment]
> Since .search() will return a maximum of 1000 results, we do not set a client side limit for .search() methods.

Am I missing something here @erlendvollset ? See my code below.

```python
len(list(client.time_series.search()))
Out[313]: 100

len(list(client.assets.search()))
Out[314]: 100

len(list(client.assets.search(limit=999)))
Out[315]: 123

len(list(client.time_series.search(limit=999)))
Out[316]: 999

len(list(client.assets.search(limit=None)))
Out[320]: 100

len(list(client.time_series.search(limit=None)))
Out[321]: 100

!pip freeze | grep cognite -i
cognite==0.0.4
cognite-logger==0.4.0
cognite-model-hosting==0.1.3
cognite-sdk==1.1.2
cognite-uploader==2.1.2
```

Passing `None` does not retrieve all results above, the limits seems to be 100. Regardless, I really think the docs or default parameters should reflect what a user can expect here.

**Comment by erlendvollset** [comment]
Agree. We should set some explicit client side limits on .search aswell.

**Comment by haakonvt** [comment]
Solved 4 years ago: https://github.com/cognitedata/cognite-sdk-python/pull/603
