### ISSUE TITLE
Inconsistent use of `include_metadata`

### ISSUE THREAD

**Issue by tommyod** [cognitedata/cognite-sdk-python#520]
**Is your feature request related to a problem? Please describe.**

Not really a problem, just an inconsistency. Consider the following:

```python
assets = client.assets.list(limit=10) # Returns object with metadata property
time_series = client.time_series.list(include_metadata=True, limit=10)
```

The method `client.assets.list` implicitly has `include_metadata` set to `True`, but the parameter doesn't exist. It's also confusing that `client.assets.list` has a parameter called `metadata`, which is unrelated to whether or not metadata is included in the results.

**Describe the solution you'd like**

I'd like `cognite.client._api.*.*API.*` methods to have as standardized signatures as possible to avoid confusion. Not identical, but as close as possible.

**Additional context**

In the process of trying to understand this, I also found the following bug:

```python
time_series = client.time_series.list(include_metadata=True, limit=10)
print(time_series.to_pandas().iloc[0, :]) # This works
print(time_series[0].to_pandas()) # This works

time_series = client.time_series.list(include_metadata=False, limit=10)
print(time_series.to_pandas().iloc[0, :]) # This works
print(time_series[0].to_pandas()) # AssertionError: Could not expand attribute 'metadata'
```

**Comment by erlendvollset** [comment]
Only the underlying time series API exposes the `include_metadata` flag, so that's why we only have it for time series. The `metadata` parameter on the list method is a filter, it can be used to filter on specific metadata values.

#521 addresses the bug.

**Comment by erlendvollset** [comment]
Will be shipped with the next release.
