### ISSUE TITLE
Improve API documentation for "List assets"

### ISSUE THREAD

**Issue by lynochka** [cognitedata/cognite-sdk-python#531]
In https://cognite-sdk-python.readthedocs-hosted.com/en/latest/cognite.html#list-assets:

I could not find any example for assets.list() with using arguemnt "root_ids" which I was told could include either {"id": 123} or {"externalId": "abc"}. 

It is not obvious what Dict in (List[Dict[str, Any]])  in the documentation could and should include and the documentation would benefit a lot from having those types of examples.

Thank you!

**Comment by sanderland** [comment]
it should probably accept two list parameters (_id and _external_id) anyway, like other functions.
