### ISSUE TITLE
Check project from login status

### ISSUE THREAD

**Issue by NilsBarlaug-cognite** [cognitedata/cognite-sdk-python#565]
**Is your feature request related to a problem? Please describe.**
If you specify a valid API key, but wrong project, login status will not give you any indication that you're authenticated to another project than what you specified.

**Describe the solution you'd like**
Either display a warning, raise an exception or change the returned object to reflect the fact that you're authenticated to the wrong project.

**Describe alternatives you've considered**

**Additional context**

**Comment by erlendvollset** [comment]
Closing as this has been adressed. A warning does get raised now.
