### ISSUE TITLE
client.asset(chunk_size=n) does not return n+x asset on last batch

### ISSUE THREAD

**Issue by CsabaAlmasi** [cognitedata/cognite-sdk-python#575]
**Describe the bug**
When calling the asset constructor with the chunk_size argument when retrieving assets the last batch is not returned unless it matches the exact chunk size >> unfilled batch is not added to the underlying generator

**To Reproduce**
```
from cognite.client import CogniteClient

client = CogniteClient()

if the actual number of assets is >2500 (example 2599) and is not divisible by chunk size the last chunk is not returned

for asset_chunk in c.assets(chunk_size=2500):
  print(asset_chunk)
## prints only the first 2500 assets

if chunk_size=<1000 it works as intended
```
also the py docs example specifically uses 2500 chunk_size which is quite misleading: https://cognite-docs.readthedocs-hosted.com/projects/cognite-sdk-python/en/latest/cognite.html#list-assets
**Expected behavior**
The generator should contain partial asset chunks not only filled batches

**System information (please complete the following information):**
- OS: [Darwin/19.0.0-x86_64-64bit]
- Python Version: [Python/3.7.3;Clang 4.0.1]
- SDK Version: [1.3.1]

**Comment by sanderland** [comment]
resolved by #576
