### ISSUE TITLE
Implement support for ignoreUnknownIds parameter where applicable

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#606]
Need an overview of which endpoints support this. Is this currently only available for assets.delete @erikgrinaker?

**Comment by erikgrinaker** [comment]
It's implemented for assets and events, get (byids) and delete endpoints. I'd recommend just searching for `ignoreUnknownIds` in the API reference: https://docs.cognite.com/api/v1/
