### ISSUE TITLE
no documentation for time_series last_updated_time

### ISSUE THREAD

**Issue by alexchandel** [cognitedata/cognite-sdk-python#641]
There is no documentation or example for the `last_updated_time` parameter for any `cognite.client.CogniteClient.time_series` method, including `time_series.list(last_updated_time=...)`.  It just says `Dict[str, Any]`, with no clues or examples what keys are needed.

**Comment by sanderland** [comment]
it's often the case that you need to look at the API documentation as well. This is particularly true for the auto-generated types/updates. List should be clearer though, so I suggest changing this to
```
            created_time (Dict[str, int]): Range between two timestamps. Possible keys are `min` and `max`, with values given as time stamps in ms.
            last_updated_time (Dict[str, int]): Range between two timestamps. Possible keys are `min` and `max`, with values given as time stamps in ms.
```
is this clear?
