### ISSUE TITLE
Update sequence columns

### ISSUE THREAD

**Issue by thomafred** [cognitedata/cognite-sdk-python#734]
**Is your feature request related to a problem? Please describe.**

I have a need to update some columns in a collection of sequences.

**Describe the solution you'd like**

Add the possibility of updating columns in `SequenceUpdate`-objects.

**Describe alternatives you've considered**

I tried the following:

```python
seq = cdf_client.sequences.retrieve(external_id=MY_EXT_ID)
seq.columns.append({
  "valueType": "INT",
  "externalId": "some-val"
})

seq = cdf_client.sequences.update(seq)
print(seq.columns) # New column does not appear
```

Workaround will be duplicating the sequence before deleting the original and recreating it with the desired updates.

**Additional context**
N/A

**Comment by haakonvt** [comment]
@thomafred Does #870 solve any part of this?

**Comment by thomafred** [comment]
yes, it seems #870 does solve this issue.

**Comment by haakonvt** [comment]
#870
