### ISSUE TITLE
Process leaking due to flawed process lifetime management

### ISSUE THREAD

**Issue by gablank** [cognitedata/cognite-sdk-python#86]
Due to how process lifetime is managed in cognite-sdk-python, spawned processes are not guaranteed to be terminated by the parent process, and may in some cases lead to "process leaks" (analogous to memory leaks). For an example of where this may happen, see [this link](https://github.com/cognitedata/cognite-sdk-python/blob/fb6724c59d363c3466fd9f71f15325bc0bbf500f/cognite/v05/timeseries.py#L110-L114). Note that this is not the only case where this pattern appears in the repository.

For example, if the call to `Pool.map` throws an exception, the part terminating the process(es) will never be called, and you have a "process leak".

This could be solved either by wrapping the code in `try...finally` or, preferably, by using a context manager.

**Comment by erlendcognite** [comment]
I believe #87 should make the required fixes.
