### ISSUE TITLE
Aggregation start time is incompatible with REST API

### ISSUE THREAD

**Issue by funsim** [cognitedata/cognite-sdk-python#909]
**System information (please complete the following information):**
 - Python Version: Python 3.9
 - SDK Version: 2.42.0

**Describe the bug**
According to the [Cognite documentation](https://docs.cognite.com/dev/concepts/aggregation/#missing-data), Cognite Data Fusion determines aggregate alignment based only on the granularity unit. If you specify hour aggregates, and the start time of the request is in the middle of the hour, the start time will be rounded up to the start time of the hour - in such a way that the **requested start time is always included**:
![image](https://user-images.githubusercontent.com/763150/160696144-4f0cc2b5-8a73-4ea3-8226-fce7489f45a4.png)

The REST API conforms to this specification, but the Python SDK does not: it rounds the start time up in such a way that the **requested start time is not always included**.

**To Reproduce**
Runnable code reproducing the error.
```
from cognite.client import CogniteClient
from cognite.client.data_classes import DatapointsQuery
import os
import pandas as pd

# Access data through SDK
api_key = os.getenv('CDF_API_KEY')
client = CogniteClient(api_key, project="fusion", client_name="simons_test")
query = DatapointsQuery(
                external_id='VAL_212_VD_9365_H03:Z.X.Value',
                start=pd.Timestamp('2021-06-23 15:24:00'),
                end=pd.Timestamp('2021-07-16 14:34:00'),
                granularity='1d',
                aggregates=['average'],
                limit=2,
            )

dps = client.datapoints.query(query)[0]
print(dps.to_pandas())
```
**Expected ouput**
```
# 2021-06-23        0.0023735657676771473
# 2021-06-24        0.0024034593881251546
```

**Observed output**
```
# 2021-06-24        0.002403
# 2021-06-25        0.002391
```

**Responsible code lines**
The problem lies in the `align_with_granularity_unit` [logic](https://github.com/cognitedata/cognite-sdk-python/blob/faaf81adf7e262642ad3944343aab421df4e3a77/cognite/client/_api/datapoints.py#L948-L952)
where the `+ gms` in the `return` statement shifts the start time such that the new start time can be above the original start time, see [here](https://github.com/cognitedata/cognite-sdk-python/blob/faaf81adf7e262642ad3944343aab421df4e3a77/cognite/client/_api/datapoints.py#L907)

**Comment by haakonvt** [comment]
Will be addressed in version 5 of the SDK. Current progress: #966

**Comment by haakonvt** [comment]
@funsim if you have time, SDK pre-release `5.0.0a1` is out and should address this issue 😄

**Comment by haakonvt** [comment]
With release `5.0.0`, the SDK behaviour now matches the API 1:1
