### ISSUE TITLE
Add a data_points_last_updated parameter for time series object 

### ISSUE THREAD

**Issue by CogJoel** [cognitedata/cognite-sdk-python#977]
**Is your feature request related to a problem? Please describe.**
It is not possible to see the latest time a time series had its data points updated. 
It comes in handy when you want to quickly filter time series that had its data points recently updated. 

**Describe the solution you'd like**
Add a parameter to the time series data class with the name data_points_last_updated(int) – The number of milliseconds since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds.
 Update it every time data points are being altered in that time series.

**Comment by erlendvollset** [comment]
This is not possible in the underlying API. So a feature request should be submitted to the time series team.
