### ISSUE TITLE
SDK segfaults when using get_datapoints function

### ISSUE THREAD

**Issue by FarbodY-Cognite** [cognitedata/cognite-sdk-python#98]
System:

MacOS 10.13.6
Python 3.7.0
pip 18.0
cognite-sdk   0.9.4

Code to reproduce:

```python
import os

import matplotlib.pyplot as plt
from cognite.config import configure_session
from cognite.v05.timeseries import get_datapoints

configure_session(api_key=os.getenv('COGNITE_API_KEY'), project='akerbp')

ts = 'equipment_x'
datapoints = get_datapoints(ts, start='52w-ago', aggregates=['avg'], granularity='1h')
```

**Comment by FarbodY-Cognite** [comment]
Seems that the part of the code that's triggering this is 

```python
num_of_processes = kwargs.get("processes", os.cpu_count())
```
in cognite.v05.timeseries. 

`os.cpu_count` doesn't seem to be working properly on MacOS.

Doing 

```datapoints = get_datapoints(ts, start='52w-ago', aggregates=['avg'], granularity='1h', processes = 1) ``` fixes this (although it's kind of a hack)

**Comment by anderscognite** [comment]
Yep, I got the same. Number of processes could be moved to `config`, but at least default to 1 until this problem is resolved...

**Comment by erlendcognite** [comment]
I have updated the methods to use ThreadPoolExecutor instead of multiprocessing. I believe this should resolve the issue. Changes found in #103 .
